language: python

python:
  - 3.7

# command to run tests
script:
  - ./run_tests.sh


before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq poppler-utils imagemagick pdftk tesseract-ocr

sudo: false

install:
  - pip install -r requirements/base.txt
